apps/eclipse-phase/src/Entity/Character.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CharacterRepository")
 * @ORM\Table(name="`character`")
 */
class Character
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private  $characterName = "";

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private  $background = null;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private  $faction = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private  $sexualIdentity = "";

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $age = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $audacityPoints = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $xp = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $aRep = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $gRep = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $cRep = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $iRep = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $eRep = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $rRep = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $fRep = 0;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $attributes = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $idInfos = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $psiPasses = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $notes = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $motivations = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Player", inversedBy="characters")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Player = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Backups", mappedBy="playableCharacter", orphanRemoval=true)
     */
    private $backups;

    public function __construct()
    {
        $this->backups = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCharacterName(): ?string
    {
        return $this->characterName;
    }

    public function setCharacterName(string $characterName): self
    {
        $this->characterName = $characterName;

        return $this;
    }

    public function getBackground(): ?string
    {
        return $this->background;
    }

    public function setBackground(?string $background): self
    {
        $this->background = $background;

        return $this;
    }

    public function getFaction(): ?string
    {
        return $this->faction;
    }

    public function setFaction(?string $faction): self
    {
        $this->faction = $faction;

        return $this;
    }

    public function getSexualIdentity(): ?string
    {
        return $this->sexualIdentity;
    }

    public function setSexualIdentity(string $sexualIdentity): self
    {
        $this->sexualIdentity = $sexualIdentity;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(?int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getAudacityPoints(): ?int
    {
        return $this->audacityPoints;
    }

    public function setAudacityPoints(int $audacityPoints): self
    {
        $this->audacityPoints = $audacityPoints;

        return $this;
    }

    public function getXp(): ?int
    {
        return $this->xp;
    }

    public function setXp(int $xp): self
    {
        $this->xp = $xp;

        return $this;
    }

    public function getARep(): ?int
    {
        return $this->aRep;
    }

    public function setARep(int $aRep): self
    {
        $this->aRep = $aRep;

        return $this;
    }

    public function getGRep(): ?int
    {
        return $this->gRep;
    }

    public function setGRep(int $gRep): self
    {
        $this->gRep = $gRep;

        return $this;
    }

    public function getCRep(): ?int
    {
        return $this->cRep;
    }

    public function setCRep(int $cRep): self
    {
        $this->cRep = $cRep;

        return $this;
    }

    public function getIRep(): ?int
    {
        return $this->iRep;
    }

    public function setIRep(int $iRep): self
    {
        $this->iRep = $iRep;

        return $this;
    }

    public function getERep(): ?int
    {
        return $this->eRep;
    }

    public function setERep(int $eRep): self
    {
        $this->eRep = $eRep;

        return $this;
    }

    public function getRRep(): ?int
    {
        return $this->rRep;
    }

    public function setRRep(int $rRep): self
    {
        $this->rRep = $rRep;

        return $this;
    }

    public function getFRep(): ?int
    {
        return $this->fRep;
    }

    public function setFRep(int $fRep): self
    {
        $this->fRep = $fRep;

        return $this;
    }

    public function getAttributes(): ?string
    {
        return $this->attributes;
    }

    public function setAttributes(?string $attributes): self
    {
        $this->attributes = $attributes;

        return $this;
    }

    public function getIdInfos(): ?string
    {
        return $this->idInfos;
    }

    public function setIdInfos(?string $idInfos): self
    {
        $this->idInfos = $idInfos;

        return $this;
    }

    public function getPsiPasses(): ?string
    {
        return $this->psiPasses;
    }

    public function setPsiPasses(?string $psiPasses): self
    {
        $this->psiPasses = $psiPasses;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getMotivations(): ?string
    {
        return $this->motivations;
    }

    public function setMotivations(?string $motivations): self
    {
        $this->motivations = $motivations;

        return $this;
    }

    public function getPlayer(): ?Player
    {
        return $this->Player;
    }

    public function setPlayer(?Player $Player): self
    {
        $this->Player = $Player;

        return $this;
    }

    /**
     * @return Collection|Backups[]
     */
    public function getBackups(): Collection
    {
        return $this->backups;
    }

    public function addBackup(Backups $backup): self
    {
        if (!$this->backups->contains($backup)) {
            $this->backups[] = $backup;
            $backup->setPlayableCharacter($this);
        }

        return $this;
    }

    public function removeBackup(Backups $backup): self
    {
        if ($this->backups->contains($backup)) {
            $this->backups->removeElement($backup);
            // set the owning side to null (unless already changed)
            if ($backup->getPlayableCharacter() === $this) {
                $backup->setPlayableCharacter(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getCharacterName();
    }
}

apps/eclipse-phase/src/Form/CharacterType.php
<?php

namespace App\Form;

use App\Entity\Character;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CharacterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('characterName')
            ->add('background')
            ->add('faction')
            ->add('sexualIdentity', ChoiceType::class,[
                'choices' => [
                    'Homme' => 'Homme',
                    'Femme' => 'Femme',
                    'Intersexué' => 'Intersexué',
                    'Neutre' => 'Neutre'
                ]
            ])
            ->add('age')
            ->add('audacityPoints')
            ->add('xp')
            ->add('motivations')
            ->add('aRep')
            ->add('gRep')
            ->add('cRep')
            ->add('iRep')
            ->add('eRep')
            ->add('rRep')
            ->add('fRep')
            ->add('attributes')
            ->add('idInfos')
            ->add('psiPasses')
            ->add('notes')
            ->add('Player')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Character::class,
        ]);
    }
}

apps/eclipse-phase/src/Controller/CharacterController.php
<?php

namespace App\Controller;

use App\Entity\Character;
use App\Form\CharacterType;
use App\Repository\CharacterRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/character")
 */
class CharacterController extends AbstractController
{
    /**
     * @Route("/", name="character_index", methods={"GET"})
     */
    public function index(CharacterRepository $characterRepository): Response
    {
        return $this->render('character/index.html.twig', [
            'characters' => $characterRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="character_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $character = new Character();
        $form = $this->createForm(CharacterType::class, $character);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($character);
            $entityManager->flush();

            return $this->redirectToRoute('character_index');
        }

        return $this->render('character/new.html.twig', [
            'character' => $character,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="character_show", methods={"GET"})
     */
    public function show(Character $character): Response
    {
        return $this->render('character/show.html.twig', [
            'character' => $character,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="character_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Character $character): Response
    {
        $form = $this->createForm(CharacterType::class, $character);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('character_index');
        }

        return $this->render('character/edit.html.twig', [
            'character' => $character,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="character_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Character $character): Response
    {
        if ($this->isCsrfTokenValid('delete'.$character->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($character);
            $entityManager->flush();
        }

        return $this->redirectToRoute('character_index');
    }
}

apps/eclipse-phase/templates/character/_delete_form.html.twig
<form method="post" action="{{ path('character_delete', {'id': character.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ character.id) }}">
    <button class="btn">{% trans %}Delete{% endtrans %}</button>
</form>

apps/eclipse-phase/templates/character/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-lg">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

apps/eclipse-phase/templates/character/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Edit Character{% endtrans %} : {{ character.characterName }}{% endblock %}

{% block body %}
    <h1>{% trans %}Edit Character{% endtrans %} : {{ character.characterName }}</h1>

    {{ include('character/_form.html.twig') }}

    <div class="back">
        <a href="{{ path('character_index') }}">
            <i class="fas fa-angle-double-left">
                {% trans %}back to list{% endtrans %}
            </i>
        </a>
    </div>

    {{ include('character/_delete_form.html.twig') }}
{% endblock %}

apps/eclipse-phase/templates/character/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Characters{% endtrans %}{% endblock %}

{% block body %}
    <h1>{% trans %}Characters{% endtrans %}</h1>

    <table class="table table-hover table-striped table-light">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans %}Character name{% endtrans %}</th>
                <th scope="col">{% trans %}Player name{% endtrans %}</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for character in characters %}
            <tr>
                <td>{{ character.characterName }}</td>
                <td>{{ character.player }}</td>
                <td>
                    <a href="{{ path('character_show', {'id': character.id}) }}">
                        <i title="{% trans %}show{% endtrans %}" class="far fa-eye"></i>
                    </a>
                    <a href="{{ path('character_edit', {'id': character.id}) }}">
                        <i title="{% trans %}edit{% endtrans %}" class="far fa-edit"></i>
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">{% trans %}No character found{% endtrans %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('character_new') }}" class="btn btn-primary btn-lg">{% trans %}Create new character{% endtrans %}</a>
{% endblock %}

apps/eclipse-phase/templates/character/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Create new character{% endtrans %}{% endblock %}

{% block body %}
    <h1>{% trans %}Create new character{% endtrans %}</h1>

    {{ include('character/_form.html.twig') }}

    <div class="back">
        <a href="{{ path('character_index') }}">
            <i class="fas fa-angle-double-left">
                {% trans %}back to list{% endtrans %}
            </i>
        </a>
    </div>
{% endblock %}

apps/eclipse-phase/templates/character/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Character{% endtrans %} : {{ character.characterName }}{% endblock %}

{% block body %}
    <h1>{% trans %}Character{% endtrans %} : {{ character.characterName }}</h1>

    <table class="table table-hover table-striped table-light">
        <tbody>
            <tr>
                <th>{% trans %}Character name{% endtrans %}</th>
                <td>{{ character.characterName }}</td>
            </tr>
            <tr>
                <th>{% trans %}Player name{% endtrans %}</th>
                <td>{{ character.player }}</td>
            </tr>
            <tr>
                <th>{% trans %}Background{% endtrans %}</th>
                <td>{{ character.background }}</td>
            </tr>
            <tr>
                <th>Faction</th>
                <td>{{ character.faction }}</td>
            </tr>
            <tr>
                <th>{% trans %}Sexual identity{% endtrans %}</th>
                <td>{{ character.sexualIdentity }}</td>
            </tr>
            <tr>
                <th>{% trans %}Age{% endtrans %}</th>
                <td>{{ character.age }}</td>
            </tr>
            <tr>
                <th>{% trans %}Audacity points{% endtrans %}</th>
                <td>{{ character.audacityPoints }}</td>
            </tr>
            <tr>
                <th>{% trans %}Xp{% endtrans %}</th>
                <td>{{ character.xp }}</td>
            </tr>
            <tr>
                <th>@-rep</th>
                <td>{{ character.aRep }}</td>
            </tr>
            <tr>
                <th>G-rep</th>
                <td>{{ character.gRep }}</td>
            </tr>
            <tr>
                <th>C-rep</th>
                <td>{{ character.cRep }}</td>
            </tr>
            <tr>
                <th>I-rep</th>
                <td>{{ character.iRep }}</td>
            </tr>
            <tr>
                <th>E-rep</th>
                <td>{{ character.eRep }}</td>
            </tr>
            <tr>
                <th>R-rep</th>
                <td>{{ character.rRep }}</td>
            </tr>
            <tr>
                <th>F-rep</th>
                <td>{{ character.fRep }}</td>
            </tr>
            <tr>
                <th>{% trans %}Attributes{% endtrans %}</th>
                <td>{{ character.attributes }}</td>
            </tr>
            <tr>
                <th>ID-Infos</th>
                <td>{{ character.idInfos }}</td>
            </tr>
            <tr>
                <th>{% trans %}Psi passes{% endtrans %}</th>
                <td>{{ character.psiPasses }}</td>
            </tr>
            <tr>
                <th>Notes</th>
                <td>{{ character.notes }}</td>
            </tr>
        </tbody>
    </table>

    <div class="back">
        <a href="{{ path('character_index') }}">
            <i class="fas fa-angle-double-left">
                {% trans %}back to list{% endtrans %}
            </i>
        </a>
    </div>

    {{ include('character/_delete_form.html.twig') }}
{% endblock %}